name: ljs-portfolio-cd

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies with yarn
        run: yarn install
        working-directory: ./frontend

      - name: Genrate build
        run: yarn build
        working-directory: ./frontend

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }} .
        working-directory: ./frontend

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }}

      - name: Access SSH and Docker-Compose run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          key: ${{ secrets.WAS_KEY }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            cd /home/ubuntu/my_project/docker-compose
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_FRONT }}
            sudo docker-compose down front
            sudo docker-compose up -d front
